In [63]:
import numpy as np
import matplotlib.pyplot as plt

In [51]:
with open('datingTestSet2.txt') as f:
    data=f.readlines()

In [52]:
data[0].strip().split('\t')

['40920', '8.326976', '0.953952', '3']

In [53]:
def file2matrix(filename):
    with open(filename) as f:
        fileData=[data.strip().split('\t') for data in f.readlines()]
        returnMat=np.array(fileData)[:,:3].astype(float)
        classLabelVector=np.array(fileData)[:,3].flatten()
    return returnMat,classLabelVector

In [56]:
returnMat,classLabelVector=file2matrix('datingTestSet2.txt')

In [57]:
returnMat

array([[4.0920000e+04, 8.3269760e+00, 9.5395200e-01],
       [1.4488000e+04, 7.1534690e+00, 1.6739040e+00],
       [2.6052000e+04, 1.4418710e+00, 8.0512400e-01],
       ...,
       [2.6575000e+04, 1.0650102e+01, 8.6662700e-01],
       [4.8111000e+04, 9.1345280e+00, 7.2804500e-01],
       [4.3757000e+04, 7.8826010e+00, 1.3324460e+00]])

In [58]:
np.unique(classLabelVector)

array(['1', '2', '3'], dtype='<U9')

In [72]:
classLabelVector[classLabelVector=='2'].astype(int)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,

In [73]:
returnMat

array([[4.0920000e+04, 8.3269760e+00, 9.5395200e-01],
       [1.4488000e+04, 7.1534690e+00, 1.6739040e+00],
       [2.6052000e+04, 1.4418710e+00, 8.0512400e-01],
       ...,
       [2.6575000e+04, 1.0650102e+01, 8.6662700e-01],
       [4.8111000e+04, 9.1345280e+00, 7.2804500e-01],
       [4.3757000e+04, 7.8826010e+00, 1.3324460e+00]])

In [75]:
classLabelVector.astype(int)

array([3, 2, 1, 1, 1, 1, 3, 3, 1, 3, 1, 1, 2, 1, 1, 1, 1, 1, 2, 3, 2, 1,
       2, 3, 2, 3, 2, 3, 2, 1, 3, 1, 3, 1, 2, 1, 1, 2, 3, 3, 1, 2, 3, 3,
       3, 1, 1, 1, 1, 2, 2, 1, 3, 2, 2, 2, 2, 3, 1, 2, 1, 2, 2, 2, 2, 2,
       3, 2, 3, 1, 2, 3, 2, 2, 1, 3, 1, 1, 3, 3, 1, 2, 3, 1, 3, 1, 2, 2,
       1, 1, 3, 3, 1, 2, 1, 3, 3, 2, 1, 1, 3, 1, 2, 3, 3, 2, 3, 3, 1, 2,
       3, 2, 1, 3, 1, 2, 1, 1, 2, 3, 2, 3, 2, 3, 2, 1, 3, 3, 3, 1, 3, 2,
       2, 3, 1, 3, 3, 3, 1, 3, 1, 1, 3, 3, 2, 3, 3, 1, 2, 3, 2, 2, 3, 3,
       3, 1, 2, 2, 1, 1, 3, 2, 3, 3, 1, 2, 1, 3, 1, 2, 3, 2, 3, 1, 1, 1,
       3, 2, 3, 1, 3, 2, 1, 3, 2, 2, 3, 2, 3, 2, 1, 1, 3, 1, 3, 2, 2, 2,
       3, 2, 2, 1, 2, 2, 3, 1, 3, 3, 2, 1, 1, 1, 2, 1, 3, 3, 3, 3, 2, 1,
       1, 1, 2, 3, 2, 1, 3, 1, 3, 2, 2, 3, 1, 3, 1, 1, 2, 1, 2, 2, 1, 3,
       1, 3, 2, 3, 1, 2, 3, 1, 1, 1, 1, 2, 3, 2, 2, 3, 1, 2, 1, 1, 1, 3,
       3, 2, 1, 1, 1, 2, 2, 3, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 2, 2, 3, 2,
       3, 3, 3, 3, 1, 2, 3, 1, 1, 1, 3, 1, 3, 2, 2,

In [149]:
import operator
def classify0(inX,dataSet,labels,k):
    datasetSize=dataSet.shape[0]    # get the number of samples
    X=np.tile(inX,(datasetSize,1))  # tile the sample and make the size equal to that of the  training dataset
    diffMat=X-dataSet
    diffMat=diffMat**2 #to square each element in the array
    sqDistance=diffMat.sum(axis=1)
    distances=np.sqrt(sqDistance)

    sortedDistanceIndices=distances.argsort() # sort the value of distances array in an ascending manner and return the corresponding index

    classCount={}
    for i in range(k):
        voteIlabel=labels[sortedDistanceIndices[i]] #get the ith element in the sortedDistances which indicate the row number of original dataset
        classCount[voteIlabel]=classCount.get(voteIlabel,0)+1

    sortedClassCount=sorted(classCount.items(),key=operator.itemgetter(1),reverse=True) # return a list of key-value tuple

    return sortedClassCount[0][0] #return the first item in the first tuple

def file2matrix(filename):
    with open(filename) as f:
        fileData=[data.strip().split('\t') for data in f.readlines()]
        returnMat=np.array(fileData)[:,:3].astype(float)
        classLabelVector=np.array(fileData)[:,3].astype(float).flatten()
        return returnMat,classLabelVector


In [150]:
def autoNorm(dataset):
    minVal=dataset.min(0)
    maxVal=dataset.max(0)
    rangeVal=maxVal-minVal
    normVal=dataset-minVal
    normVal=normVal/rangeVal
    return minVal,maxVal,normVal

In [87]:
minVal,maxVal,rangeVal,normVal=autoNorm(returnMat)

In [88]:
minVal

array([0.      , 0.      , 0.001156])

In [89]:
maxVal

array([9.1273000e+04, 2.0919349e+01, 1.6955170e+00])

In [90]:
rangeVal

array([9.1273000e+04, 2.0919349e+01, 1.6943610e+00])

In [91]:
normVal

array([[0.44832535, 0.39805139, 0.56233353],
       [0.15873259, 0.34195467, 0.98724416],
       [0.28542943, 0.06892523, 0.47449629],
       ...,
       [0.29115949, 0.50910294, 0.51079493],
       [0.52711097, 0.43665451, 0.4290048 ],
       [0.47940793, 0.3768091 , 0.78571804]])

In [165]:
def datingClassTest():
    datingDataMat,datingLabels=file2matrix('datingTestSet2.txt')
    hoRatio=0.1
    dataNum=len(datingDataMat)
    trainingNum=dataNum-int(dataNum*0.1)
    testingNum=int(dataNum*0.1)
    
    indx=list(range(datingDataMat.shape[0]))
    np.random.shuffle(indx)
    datingDataMat=datingDataMat[indx]
    datingLabels=datingLabels[indx]
    minVal,maxVal,normVal=autoNorm(datingDataMat)
    
    X_train,y_train,X_test,y_test=normVal[:trainingNum],datingLabels[:trainingNum],+\
                                  normVal[trainingNum:],datingLabels[trainingNum:]
    correctNum=0
    for indx,testData in enumerate(X_test):
        y_pred=classify0(testData,X_train,y_train,3)
        y_true=y_test[indx]
        if y_pred==y_true:
            correctNum+=1
    
    acc=correctNum/testingNum    
    return X_train,y_train,X_test,y_test,acc

In [172]:
acc

0.97

In [166]:
X_train,y_train,X_test,y_test,acc=datingClassTest()

In [167]:
y_test

array([2., 3., 2., 3., 1., 2., 1., 1., 3., 2., 2., 2., 3., 2., 2., 1., 1.,
       1., 1., 3., 1., 2., 2., 1., 3., 1., 1., 1., 2., 2., 2., 2., 3., 1.,
       2., 3., 1., 3., 3., 3., 3., 1., 3., 1., 3., 1., 3., 2., 1., 1., 3.,
       2., 2., 1., 3., 1., 2., 3., 1., 1., 1., 3., 3., 1., 2., 1., 3., 1.,
       3., 1., 2., 1., 2., 3., 3., 3., 2., 1., 3., 3., 1., 3., 1., 3., 2.,
       1., 2., 3., 3., 1., 2., 3., 3., 2., 1., 2., 2., 1., 3., 2.])

In [168]:
X_train.shape

(900, 3)

In [169]:
X_test.shape

(100, 3)

In [170]:
datingDataMat[:4]

array([[3.1054000e+04, 1.1508473e+01, 1.6242960e+00],
       [4.6696000e+04, 1.2666325e+01, 9.3196000e-01],
       [1.6674000e+04, 4.1839970e+00, 1.2752900e+00],
       [1.3499000e+04, 5.8569020e+00, 3.6388300e-01]])

In [171]:
datingLabels[indx]

array([3., 2., 2., 3., 3., 1., 2., 3., 2., 3., 2., 3., 3., 1., 3., 3., 2.,
       2., 3., 3., 2., 3., 3., 2., 1., 1., 1., 2., 3., 3., 3., 2., 2., 1.,
       1., 2., 2., 3., 3., 2., 1., 1., 1., 2., 1., 3., 2., 3., 3., 1., 2.,
       3., 2., 1., 3., 2., 1., 2., 2., 1., 3., 2., 2., 2., 1., 2., 1., 3.,
       1., 2., 1., 1., 1., 3., 2., 1., 3., 3., 1., 2., 3., 1., 1., 2., 2.,
       1., 3., 2., 2., 3., 3., 2., 2., 2., 2., 3., 1., 1., 1., 1., 2., 1.,
       3., 1., 1., 2., 1., 1., 1., 3., 1., 2., 1., 2., 3., 2., 3., 1., 3.,
       2., 2., 3., 1., 2., 3., 3., 3., 3., 3., 2., 2., 3., 2., 3., 3., 2.,
       1., 3., 1., 3., 2., 2., 3., 1., 3., 1., 1., 2., 1., 1., 2., 1., 3.,
       3., 2., 1., 1., 2., 2., 3., 1., 1., 3., 3., 2., 1., 2., 3., 1., 3.,
       2., 1., 1., 3., 2., 1., 1., 1., 1., 1., 1., 2., 3., 2., 1., 1., 3.,
       1., 1., 3., 2., 1., 1., 2., 3., 1., 2., 1., 2., 3., 2., 1., 1., 2.,
       3., 2., 3., 1., 1., 2., 1., 1., 1., 2., 2., 1., 2., 2., 2., 3., 3.,
       1., 1., 1., 2., 1.

In [135]:
normVal

array([[0.34023205, 0.55013533, 0.95796586],
       [0.51160803, 0.60548371, 0.549354  ],
       [0.18268272, 0.20000608, 0.75198497],
       ...,
       [0.44905942, 0.5178578 , 0.93502506],
       [0.85044865, 0.76749582, 0.31864284],
       [0.54187985, 0.40009213, 0.38689571]])

In [155]:
y_test

2.0